owner: GraditiPro
repo: standshare-status-dev

sites:
  - name: Web App
    url: https://demo.dev.standshare.app
  - name: API
    url: https://api.dev.standshare.app/health
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"degraded"'
  - name: Admin Portal
    url: https://admin.dev.standshare.app
  - name: Admin API
    url: https://admin-api.dev.standshare.app/health
    expectedStatusCodes:
      - 200
    __dangerous__body_down: '"status":"degraded"'

status-website:
  cname: status.dev.standshare.app
  logoUrl: https://raw.githubusercontent.com/GraditiPro/standshare-status-dev/master/standshare_logo.jpg
  favicon: https://raw.githubusercontent.com/GraditiPro/standshare-status-dev/master/standshare_logo.jpg
  name: StandShare Status (Dev)
  introTitle: "**StandShare Dev** service status and uptime monitor."
  introMessage: Real-time status for all StandShare development environment services. Powered by [Upptime](https://github.com/upptime/upptime).
  theme: night
  css: "\n
    :root {
    --color-primary: #1F4FD8;
    --color-success: #1E6A57;
    }\n
    .navbar { background-color: #0F2D46 !important; }\n
    a { color: #1F4FD8; }\n
    a:hover { color: #C8A951; }\n"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
